/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client_server;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.net.Socket;
import static java.nio.file.Files.list;
import static java.rmi.Naming.list;
import java.rmi.UnknownHostException;
import static java.util.Collections.list;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryan
 */
public class AplikasiChatting extends javax.swing.JFrame implements Runnable {
    
    ServerSocket server;
    Socket client;
    BufferedReader in_server;
    BufferedWriter out_server;

    /**
     * Creates new form AplikasiChatting
     */
    public AplikasiChatting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        cb_pilih = new javax.swing.JComboBox<>();
        btn_mulai = new javax.swing.JButton();
        txtChat = new javax.swing.JTextField();
        btn_kirim = new javax.swing.JButton();
        list = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb_pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Server", "Client" }));
        cb_pilih.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_pilihItemStateChanged(evt);
            }
        });
        cb_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pilihActionPerformed(evt);
            }
        });

        btn_mulai.setText("MULAI");
        btn_mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mulaiActionPerformed(evt);
            }
        });

        btn_kirim.setText("KIRIM");
        btn_kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kirimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(list, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cb_pilih, 0, 258, Short.MAX_VALUE)
                        .addComponent(txtChat)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_mulai, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btn_kirim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_pilih, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mulai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_kirim, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtChat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kirimActionPerformed

        try {
            out_server.write(txtChat.getText());
            out_server.newLine();
            out_server.flush();
            list.add(txtChat.getText());
            txtChat.setText(" ");
        } catch (IOException ex) {
            Logger.getLogger(AplikasiChatting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_kirimActionPerformed

    private void cb_pilihItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_pilihItemStateChanged
    if (cb_pilih.getSelectedItem().equals("Server")){
        btn_mulai.setText("Start");
    } else {
        
        btn_mulai.setText("Connect");
    }
    }//GEN-LAST:event_cb_pilihItemStateChanged

    private void btn_mulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mulaiActionPerformed
        if (btn_mulai.getText().equals("Start")){
            koneksi_server();
            Thread t = new Thread(this);
            t.start();
        } else {
            koneksi_client();
            Thread t = new Thread(this);
            t.start();
        }
        
    }//GEN-LAST:event_btn_mulaiActionPerformed

    private void cb_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_pilihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiChatting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiChatting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiChatting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiChatting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiChatting().setVisible(true);
            }
        });
    }
    
    
    public void koneksi_server(){
    
        try {
            server = new ServerSocket(2000);
            this.setTitle("Menunggu Koneksi");
        } catch (IOException ex) {
            System.out.println("Koneksi Error");
        }
    
        try {
            client = server.accept();
            this.setTitle("Koneksi Diterima");
        } catch (IOException ex) {
            System.out.println("Koneksi Error");
        }
        
        try {
            in_server = new BufferedReader(new InputStreamReader(client.getInputStream()));
        } catch (IOException ex) {
            System.out.println("Koneksi error");
        }
        try {
            out_server = new BufferedWriter (new OutputStreamWriter(client.getOutputStream()));
        } catch (IOException ex) {
            System.out.println("Koneksi error");
        }
        
    }
    
    public void koneksi_client(){
        String ip_address = JOptionPane.showInputDialog("Masukkan IP Address tujuan server");
        try {
            client = new Socket(ip_address,2000);
        } catch (UnknownHostException ex) {
            System.out.println("Koneksi Error");
        } catch (IOException ex){
            System.out.println("Koneksi error");
        }
        
        try {
            in_server = new BufferedReader(new InputStreamReader(client.getInputStream()));
        } catch (IOException ex) {
            System.out.println("Koneksi error");
        }
        try {
            out_server = new BufferedWriter (new OutputStreamWriter(client.getOutputStream()));
        } catch (IOException ex) {
            System.out.println("Koneksi error");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kirim;
    private javax.swing.JButton btn_mulai;
    private javax.swing.JComboBox<String> cb_pilih;
    private java.awt.List list;
    private java.awt.List list1;
    private javax.swing.JTextField txtChat;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true){
            try {
                list.add(in_server.readLine());
            } catch (IOException ex) {
                Logger.getLogger(AplikasiChatting.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private static class list {

        private static void add(String readLine) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public list() {
        }
    }
}
